/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as GenresIndexRouteImport } from './routes/genres/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as AlbumArtistsIndexRouteImport } from './routes/albumArtists/index'
import { Route as PlaylistsNameRouteImport } from './routes/playlists/$name'
import { Route as AlbumsIdRouteImport } from './routes/albums/$id'
import { Route as GenresIdNameRouteImport } from './routes/genres/$id.$name'
import { Route as ArtistsIdNameRouteImport } from './routes/artists/$id.$name'
import { Route as AlbumArtistsIdNameRouteImport } from './routes/albumArtists/$id.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumArtistsIndexRoute = AlbumArtistsIndexRouteImport.update({
  id: '/albumArtists/',
  path: '/albumArtists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsNameRoute = PlaylistsNameRouteImport.update({
  id: '/playlists/$name',
  path: '/playlists/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIdRoute = AlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIdNameRoute = GenresIdNameRouteImport.update({
  id: '/genres/$id/$name',
  path: '/genres/$id/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdNameRoute = ArtistsIdNameRouteImport.update({
  id: '/artists/$id/$name',
  path: '/artists/$id/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumArtistsIdNameRoute = AlbumArtistsIdNameRouteImport.update({
  id: '/albumArtists/$id/$name',
  path: '/albumArtists/$id/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/playlists/$name': typeof PlaylistsNameRoute
  '/albumArtists': typeof AlbumArtistsIndexRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/genres': typeof GenresIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/albumArtists/$id/$name': typeof AlbumArtistsIdNameRoute
  '/artists/$id/$name': typeof ArtistsIdNameRoute
  '/genres/$id/$name': typeof GenresIdNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/playlists/$name': typeof PlaylistsNameRoute
  '/albumArtists': typeof AlbumArtistsIndexRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/genres': typeof GenresIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/albumArtists/$id/$name': typeof AlbumArtistsIdNameRoute
  '/artists/$id/$name': typeof ArtistsIdNameRoute
  '/genres/$id/$name': typeof GenresIdNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/playlists/$name': typeof PlaylistsNameRoute
  '/albumArtists/': typeof AlbumArtistsIndexRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/albumArtists/$id/$name': typeof AlbumArtistsIdNameRoute
  '/artists/$id/$name': typeof ArtistsIdNameRoute
  '/genres/$id/$name': typeof GenresIdNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums/$id'
    | '/playlists/$name'
    | '/albumArtists'
    | '/albums'
    | '/artists'
    | '/genres'
    | '/playlists'
    | '/albumArtists/$id/$name'
    | '/artists/$id/$name'
    | '/genres/$id/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums/$id'
    | '/playlists/$name'
    | '/albumArtists'
    | '/albums'
    | '/artists'
    | '/genres'
    | '/playlists'
    | '/albumArtists/$id/$name'
    | '/artists/$id/$name'
    | '/genres/$id/$name'
  id:
    | '__root__'
    | '/'
    | '/albums/$id'
    | '/playlists/$name'
    | '/albumArtists/'
    | '/albums/'
    | '/artists/'
    | '/genres/'
    | '/playlists/'
    | '/albumArtists/$id/$name'
    | '/artists/$id/$name'
    | '/genres/$id/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsIdRoute: typeof AlbumsIdRoute
  PlaylistsNameRoute: typeof PlaylistsNameRoute
  AlbumArtistsIndexRoute: typeof AlbumArtistsIndexRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  GenresIndexRoute: typeof GenresIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  AlbumArtistsIdNameRoute: typeof AlbumArtistsIdNameRoute
  ArtistsIdNameRoute: typeof ArtistsIdNameRoute
  GenresIdNameRoute: typeof GenresIdNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albumArtists/': {
      id: '/albumArtists/'
      path: '/albumArtists'
      fullPath: '/albumArtists'
      preLoaderRoute: typeof AlbumArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$name': {
      id: '/playlists/$name'
      path: '/playlists/$name'
      fullPath: '/playlists/$name'
      preLoaderRoute: typeof PlaylistsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$id': {
      id: '/albums/$id'
      path: '/albums/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AlbumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$id/$name': {
      id: '/genres/$id/$name'
      path: '/genres/$id/$name'
      fullPath: '/genres/$id/$name'
      preLoaderRoute: typeof GenresIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$id/$name': {
      id: '/artists/$id/$name'
      path: '/artists/$id/$name'
      fullPath: '/artists/$id/$name'
      preLoaderRoute: typeof ArtistsIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albumArtists/$id/$name': {
      id: '/albumArtists/$id/$name'
      path: '/albumArtists/$id/$name'
      fullPath: '/albumArtists/$id/$name'
      preLoaderRoute: typeof AlbumArtistsIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsIdRoute: AlbumsIdRoute,
  PlaylistsNameRoute: PlaylistsNameRoute,
  AlbumArtistsIndexRoute: AlbumArtistsIndexRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  GenresIndexRoute: GenresIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  AlbumArtistsIdNameRoute: AlbumArtistsIdNameRoute,
  ArtistsIdNameRoute: ArtistsIdNameRoute,
  GenresIdNameRoute: GenresIdNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
